---
title: "lab 10 comments"
author: "Celeste!"
date: "2023-12-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing libraries

```{r lib}
library(tidyverse)
library(readxl)
```

## Prepareing data

```{r prep, echo=FALSE}
forex <- read_excel("data/Exchange_Rate_Report.xlsx", skip = 2)%>%
  rename(date='Date',
         rate='Euro   (EUR)',
         usd='U.S. dollar   (USD)')%>%
  select(date,rate)%>%
  mutate(date=as.Date(date,format="%Y-%m-%d"))%>%
  filter(!is.na(rate))%>%
  mutate(g=(rate - lag(rate, n = 1))/lag(rate, n = 1))%>%
  filter(!is.na(g))
```

## Plotting figure 1

```{r Fig 1}
ggplot(forex, aes(x = date, y = rate))+
  geom_line(stat='identity', lwd = 1)+
  scale_x_date(date_breaks = "24 month", date_labels = "%Y")+
  xlab("") +
  ylab("USD/EUR") +
  labs(title = "EUR against the US dollar, 2000-2023",
       caption = "Source: International Monetary Fund. Series: Representative rates.")+
  theme(plot.title = element_text(size=22),
        plot.subtitle = element_text(size=16),
        legend.title = element_blank(),
        legend.text=element_text(size=14),
        legend.position="bottom",
        plot.caption = element_text(size=12, hjust = 0),
        axis.title = element_text(size = 18),
        strip.background = element_blank(),
        axis.text.x=element_text(angle=45, hjust=1, size = 12),
        axis.text.y=element_text(size = 12),
        strip.placement = "outside",
        panel.grid.minor = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.grid.major = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.background = element_rect(fill = "transparent", colour = NA),
        plot.background  = element_rect(fill = "transparent", colour = NA),
        legend.background = element_rect(fill='transparent'),
        legend.key=element_blank())
```

## Plotting figure 2

```{r}
ggplot(forex, aes(x = date, y = g))+
  geom_line(lwd = 0.5)+
  scale_x_date(date_breaks = "24 month", date_labels = "%Y")+
  xlab("") +
  ylab("Daily rate of change") +
  labs(title = "EUR against the US dollar, 2000-2023",
       caption = "Source: International Monetary Fund. Series: Representative rates.")+
  theme(plot.title = element_text(size=22),
        plot.subtitle = element_text(size=16),
        legend.title = element_blank(),
        legend.text=element_text(size=14),
        legend.position="bottom",
        plot.caption = element_text(size=12, hjust = 0),
        axis.title = element_text(size = 18),
        strip.background = element_blank(),
        axis.text.x=element_text(size = 14, angle=45, hjust=1),
        axis.text.y=element_text(size = 8.75),
        strip.placement = "outside",
        panel.grid.minor = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.grid.major = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.background = element_rect(fill = "transparent", colour = NA),
        plot.background  = element_rect(fill = "transparent", colour = NA),
        legend.background = element_rect(fill='transparent'),
        legend.key=element_blank())
```

## Plotting figure 3

```{r}
ggplot(forex, aes(x = date, y = g))+
  geom_point()+
  scale_x_date(date_breaks = "24 month", date_labels = "%Y")+
  xlab("") +
  ylab("Daily rate of change") +
  labs(title = "EUR against the US dollar, 2000-2023",
       caption = "Source: International Monetary Fund. Series: Representative rates.")+
  theme(plot.title = element_text(size=22),
        plot.subtitle = element_text(size=16),
        legend.title = element_blank(),
        legend.text=element_text(size=14),
        legend.position="bottom",
        plot.caption = element_text(size=12, hjust = 0),
        axis.title = element_text(size = 18),
        strip.background = element_blank(),
        axis.text.x=element_text(size = 14, angle=45, hjust=1),
        axis.text.y=element_text(size = 8.75),
        strip.placement = "outside",
        panel.grid.minor = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.grid.major = element_line('grey', size = 0.1, linetype = 'dashed'),
        panel.background = element_rect(fill = "transparent", colour = NA),
        plot.background  = element_rect(fill = "transparent", colour = NA),
        legend.background = element_rect(fill='transparent'),
        legend.key=element_blank())
```

## Comments

The data are from IMF exchange rate(International Monetary Fund, 2023), using EUR against USD as exchange rate.

Ranging from January 1995 to December 2023, period are chose to align with the plots in the lab instruction.
